/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DronEstandar;
import Model.Sede;
import Model.Dron;
import Repository.Data;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Roldán José
 */
public class GestionDronesSedesView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionDronesSedesView.class.getName());

    public GestionDronesSedesView() {
        initComponents();
        inicializarSedesMundial(); 
        actualizarComboSedes();
        
        // CORRECCIÓN: Llamamos a limpiar en lugar de actualizar al iniciar
        limpiarTabla(); 
    }

    private void limpiarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaInventario.getModel();
        modelo.setRowCount(0);
    }

    // Este método lo puedes llamar cuando quieras ver los datos (ej. al presionar un botón)
   public void actualizarTablas() {
    DefaultTableModel modelo = (DefaultTableModel) tablaInventario.getModel();
    modelo.setRowCount(0); // Esto borra todas las filas actuales de la tabla en pantalla

    // Volvemos a insertar solo lo que está en las listas actuales de Data
    for (Sede s : Data.sedes) {
        modelo.addRow(new Object[]{"Sede", s.getCodigo(), s.getNombre(), s.getCiudad(), "Disponible"});
    }

    for (Dron d : Data.drones) {
        // Lógica para obtener el nombre de la sede del dron
        String nombreSede = (d instanceof DronEstandar && ((DronEstandar) d).getSede() != null) 
                            ? ((DronEstandar) d).getSede().getNombre() : "N/A";
        
        modelo.addRow(new Object[]{"Dron", d.getCodigo(), d.getModelo(), nombreSede, (int)d.getNivelBateria() + " min"});
    }
}

    private void inicializarSedesMundial() {
        String[] sedesMundial = {
            "MetLife Stadium", "SoFi Stadium", "AT&T Stadium", "Arrowhead Stadium", 
            "Mercedes-Benz Stadium", "NRG Stadium", "Lincoln Financial Field", 
            "Gillette Stadium", "Levi's Stadium", "Lumen Field", "Hard Rock Stadium", 
            "Estadio Azteca", "Estadio BBVA", "Estadio Akron"
        };

        for (String nombre : sedesMundial) {
            boolean existe = false;
            for (Sede s : Data.sedes) {
                if (s.getNombre().equalsIgnoreCase(nombre)) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                Data.sedes.add(new Sede("ID-" + nombre.substring(0, 3).toUpperCase(), nombre, "Sede Mundial", 0));
            }
        }
    }

    private void actualizarComboSedes() {
        cmbSedes.removeAllItems();
        cmbSedes.addItem("Seleccione una sede...");
        for (Sede s : Data.sedes) {
            cmbSedes.addItem(s.getNombre());
        }
    }
   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarSede = new javax.swing.JButton();
        btnRegistrarDron = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtCodigoSede = new javax.swing.JTextField();
        txtNombreSede = new javax.swing.JTextField();
        txtCiudadSede = new javax.swing.JTextField();
        txtCodigoDron = new javax.swing.JTextField();
        txtModeloDron = new javax.swing.JTextField();
        txtCapacidadSede = new javax.swing.JTextField();
        cmbSedes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrarSede.setText("Registrar Sede");
        btnRegistrarSede.addActionListener(this::btnRegistrarSedeActionPerformed);

        btnRegistrarDron.setText("Registrar Dron");
        btnRegistrarDron.addActionListener(this::btnRegistrarDronActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        txtNombreSede.addActionListener(this::txtNombreSedeActionPerformed);

        txtCodigoDron.addActionListener(this::txtCodigoDronActionPerformed);

        txtCapacidadSede.addActionListener(this::txtCapacidadSedeActionPerformed);

        cmbSedes.addActionListener(this::cmbSedesActionPerformed);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Categoria", "Codigo / ID Dron", "Nombre / Modelo", "Ciudad / Sede", "Estado / Autonomía"
            }
        ));
        jScrollPane1.setViewportView(tablaInventario);

        jLabel1.setText("Código de Sede:");

        jLabel2.setText("Nombre de la Sede:");

        jLabel3.setText("Ciudad/Ubicación:");

        jLabel4.setText("ID/Serie del Dron:");

        jLabel5.setText("Modelo:");

        jLabel6.setText("Autonomía (min):");

        jLabel7.setText("Asignar a Sede:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCiudadSede, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(txtCodigoSede)
                        .addComponent(txtNombreSede)
                        .addComponent(txtCodigoDron)
                        .addComponent(txtModeloDron)
                        .addComponent(txtCapacidadSede))
                    .addComponent(cmbSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(btnRegistrarSede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarDron)
                .addGap(213, 213, 213))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(347, 347, 347))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudadSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoDron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModeloDron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCapacidadSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarSede)
                    .addComponent(btnRegistrarDron))
                .addGap(42, 42, 42)
                .addComponent(btnRegresar)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSedeActionPerformed
     if (txtCodigoSede.getText().trim().isEmpty() || 
        txtNombreSede.getText().trim().isEmpty() || 
        txtCiudadSede.getText().trim().isEmpty()) { 
        
        JOptionPane.showMessageDialog(this, "Completa los campos de la sede.");
        return;
    }
    
    // Asumimos un valor por defecto o creamos un campo exclusivo para capacidad
    int capacidad = 0; 
    try {
        capacidad = Integer.parseInt(txtCapacidadSede.getText());
    } catch (NumberFormatException e) {
        // Si no es un número, dejamos 0 o lanzamos aviso
    }

    Data.sedes.add(new Sede(txtCodigoSede.getText(), txtNombreSede.getText(), txtCiudadSede.getText(), capacidad));
    actualizarTablas();
    actualizarComboSedes();
    JOptionPane.showMessageDialog(this, "Sede registrada.");

    
    }//GEN-LAST:event_btnRegistrarSedeActionPerformed

    private void btnRegistrarDronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDronActionPerformed

    if (cmbSedes.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una sede válida.");
            return;
        }

        String nombreSede = cmbSedes.getSelectedItem().toString();
        Sede sedeAsignada = null;
        for (Sede s : Data.sedes) {
            if (s.getNombre().equalsIgnoreCase(nombreSede)) {
                sedeAsignada = s;
                break;
            }
        }

        try {
            double autonomia = Double.parseDouble(txtCapacidadSede.getText().trim());
            Data.drones.add(new DronEstandar(txtCodigoDron.getText(), txtModeloDron.getText(), autonomia, "Disponible", "Estándar", sedeAsignada));
            actualizarTablas();
            JOptionPane.showMessageDialog(this, "Dron registrado correctamente.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: La autonomía debe ser un número.");
        }
    
    }//GEN-LAST:event_btnRegistrarDronActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtNombreSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSedeActionPerformed

    private void txtCodigoDronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDronActionPerformed

    private void txtCapacidadSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadSedeActionPerformed

    private void cmbSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSedesActionPerformed
  
    }//GEN-LAST:event_cmbSedesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionDronesSedesView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDron;
    private javax.swing.JButton btnRegistrarSede;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbSedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtCapacidadSede;
    private javax.swing.JTextField txtCiudadSede;
    private javax.swing.JTextField txtCodigoDron;
    private javax.swing.JTextField txtCodigoSede;
    private javax.swing.JTextField txtModeloDron;
    private javax.swing.JTextField txtNombreSede;
    // End of variables declaration//GEN-END:variables
}
