/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Roldán José
 */

public class MainMenuView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuView.class.getName());

    /**
     * Creates new form MainMenuView
     */
   public MainMenuView(Model.Usuario usuarioLogueado) {
    initComponents();
    lblBienvenida.setText("Usuario: " + usuarioLogueado.getNombres() + " " + usuarioLogueado.getApellidos() + " | Rol: " + usuarioLogueado.getRol());
    
    if (usuarioLogueado.getRol().equals("Administrador")) {
        btnDronesSedes.setEnabled(false);
        btnMisionesRutas.setEnabled(false);
    } else if (usuarioLogueado.getRol().equals("Supervisor")) {
        btnUsuarios.setEnabled(false);
        btnMisionesRutas.setEnabled(false);
    } else if (usuarioLogueado.getRol().equals("Operador")) {
        btnUsuarios.setEnabled(false);
        btnDronesSedes.setEnabled(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnDronesSedes = new javax.swing.JButton();
        btnMisionesRutas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA DE GESTIÓN DE DRONES - MUNDIAL 2026");

        lblBienvenida.setText("jLabel2");

        btnUsuarios.setText("Gestionar Usuarios");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        btnDronesSedes.setText("Gestionar Drones y Sedes");
        btnDronesSedes.addActionListener(this::btnDronesSedesActionPerformed);

        btnMisionesRutas.setText("Gestionar Misiones y Rutas");
        btnMisionesRutas.addActionListener(this::btnMisionesRutasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDronesSedes)
                            .addComponent(btnUsuarios)
                            .addComponent(btnMisionesRutas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDronesSedes)
                .addGap(18, 18, 18)
                .addComponent(btnMisionesRutas)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
      GestionUsuariosView ventanaUsuarios = new GestionUsuariosView();
ventanaUsuarios.setLocationRelativeTo(null);
ventanaUsuarios.setVisible(true);

    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnDronesSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDronesSedesActionPerformed
       GestionDronesSedesView ventanaDrones = new GestionDronesSedesView();
    
    ventanaDrones.setLocationRelativeTo(null);
   
    ventanaDrones.setVisible(true);
    }//GEN-LAST:event_btnDronesSedesActionPerformed

    private void btnMisionesRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisionesRutasActionPerformed
     GestionMisionesView ventanaMisiones = new GestionMisionesView();
    ventanaMisiones.setLocationRelativeTo(null);
    ventanaMisiones.setVisible(true);
    }//GEN-LAST:event_btnMisionesRutasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDronesSedes;
    private javax.swing.JButton btnMisionesRutas;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
